export type ApiSuccess<T> = { success: true; data: T };
export type ApiError = {
  success: false;
  error: { code: string; message: string; details?: unknown };
};
export type ApiResponse<T> = ApiSuccess<T> | ApiError;

/** Central catalog of audit/security event types (see docs/security/threat-model.md). */
export const SecurityEventType = {
  USER_REGISTERED: "USER_REGISTERED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_CHALLENGE_ISSUED: "LOGIN_CHALLENGE_ISSUED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  EMAIL_CHANGE_REQUESTED: "EMAIL_CHANGE_REQUESTED",
  EMAIL_CHANGED: "EMAIL_CHANGED",
  TOTP_ENROLLMENT_STARTED: "TOTP_ENROLLMENT_STARTED",
  TOTP_ENABLED: "TOTP_ENABLED",
  TOTP_FAILED: "TOTP_FAILED",
  TOTP_SUCCESS: "TOTP_SUCCESS",
  RECOVERY_CODE_USED: "RECOVERY_CODE_USED",
  RECOVERY_CODES_REGENERATED: "RECOVERY_CODES_REGENERATED",
  TWO_FACTOR_DISABLED: "TWO_FACTOR_DISABLED",
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_REVOKED: "SESSION_REVOKED",
  ALL_SESSIONS_REVOKED: "ALL_SESSIONS_REVOKED",
  REFRESH_TOKEN_REUSE_DETECTED: "REFRESH_TOKEN_REUSE_DETECTED",
  SUSPICIOUS_LOGIN: "SUSPICIOUS_LOGIN",
  TRUSTED_DEVICE_ADDED: "TRUSTED_DEVICE_ADDED",
  TRUSTED_DEVICE_REVOKED: "TRUSTED_DEVICE_REVOKED",
  ACCOUNT_LOCKED_TEMPORARILY: "ACCOUNT_LOCKED_TEMPORARILY",
} as const;
export type SecurityEventType = (typeof SecurityEventType)[keyof typeof SecurityEventType];

export const Role = { USER: "USER", ADMIN: "ADMIN" } as const;
export type Role = (typeof Role)[keyof typeof Role];
